name: kamao
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  http: ^1.2.2
  get_storage: ^2.1.1
  logger: ^2.4.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  lottie: ^3.1.2

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animation/

